App\Entity\Article:
  type: entity
  table: article
  repositoryClass: App\Repository\ArticleRepository

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    title:
      type: string
      length: 255
      nullable: false

    content:
      type: text
      nullable: false

  manyToOne:
    author:
      targetEntity: App\Entity\User
      inversedBy: articles
      joinColumn:
        name: author_id
        nullable: false
        referencedColumnName: id

    category:
      targetEntity: App\Entity\Category
      inversedBy: articles
      joinColumn:
        name: category_id
        nullable: false
        referencedColumnName: id

  oneToMany:
    comments:
      targetEntity: App\Entity\Comment
      mappedBy: article

  manyToMany:
    tags:
      targetEntity: App\Entity\Tag
      inversedBy: articles
      joinTable:
        name: article_tags
        joinColumns:
          article_id:
            referencedColumnName: id
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id
