App\Entity\Tag:
  type: entity
  table: tag
  repositoryClass: App\Repository\TagRepository

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    name:
      type: string
      length: 255
      nullable: false
      unique: true

  manyToMany:
    articles:
      targetEntity: App\Entity\Article
      mappedBy: tags
