App\Entity\User:
  type: entity
  table: user

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    login:
      type: string
      length: 255
      nullable: true
      unique: true

    email:
      type: string
      length: 255
      nullable: true
      unique: true

    public:
      type: string
      length: 255
      nullable: false
      unique: true

    roles:
      type: simple_array
      length: 255
      nullable: false

    password:
      type: string
      length: 255
      nullable: false

    data:
      type: json
      nullable: false

  oneToMany:
    articles:
      targetEntity: App\Entity\Article
      mappedBy: author

    comments:
      targetEntity: App\Entity\Comment
      mappedBy: author
