login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

register:
    path: /register
    controller: App\Controller\SecurityController::register
    methods: [GET]

register_submit:
    path: /register
    controller: App\Controller\SecurityController::register_submit

article_view:
    path: /view/{id}
    controller: App\Controller\ArticleController::view
    requirements:
        id: '\d+'

article_write:
    path: /write/{id}
    controller: App\Controller\ArticleController::write
    methods: [GET]
    requirements:
        id: '\d+'
    defaults:
        id: null

article_write_submit:
    path: /write/{id}
    controller: App\Controller\ArticleController::write_submit
    methods: [POST]
    requirements:
        id: '\d+'
    defaults:
        id: null

comment_write_submit:
    path: /comment/{article}
    controller: App\Controller\CommentController::write_submit
    methods: [POST]
    requirements:
        article: '\d+'

tag_articles:
    path: /tag/{name}
    controller: App\Controller\TagController::tag
    requirements:
        tag: '\w+'

blog_list:
    path: /{category}
    controller: App\Controller\BlogController::list
    methods: [GET]
    requirements:
        category: '\w+'
    defaults:
        category: null
        page: 1

blog_list_pagination:
    path: /{category}/page-{page}
    controller: App\Controller\BlogController::list
    methods: [GET]
    requirements:
        category: '\w+'
        page: '[1-9]\d*'
