article_write:
    path: /write/{id}
    controller: App\Controller\ArticleController::write
    methods: [GET]
    requirements:
        id: '\d+'
    defaults:
        id: null

article_view_submit:
    path: /write/{id}
    controller: App\Controller\ArticleController::write_submit
    methods: [POST]
    requirements:
        id: '\d+'
    defaults:
        id: null

blog_list:
    path: /{month}
    controller: App\Controller\BlogController::list
    requirements:
        month: '\d{4}-\d{2}'
    defaults:
        category: null
        month: null
        page: 1

blog_list_pagination:
    path: /{month}/page-{page}
    controller: App\Controller\BlogController::list
    requirements:
        month: '\d{4}-\d{2}'
        page: '[1-9]\d*'
    defaults:
        category: null

blog_category:
    path: /{category}/{month}
    controller: App\Controller\BlogController::list
    requirements:
        category: '\w+'
        month: '\d{4}-\d{2}'
    defaults:
        month: null
        page: 1

blog_category_pagination:
    path: /{category}/{month}/page-{page}
    controller: App\Controller\BlogController::list
    requirements:
        category: '\w+'
        month: '\d{4}-\d{2}'
        page: '[1-9]\d*'

# tag_articles:
#     path: /tag/{name}
#     controller: App\Controller\TagController::tag
#     requirements:
#         tag: '\w+'

# article_view:
#     path: /view/{id}
#     controller: App\Controller\ArticleController::view
#     requirements:
#         id: '\d+'
